### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by juanchristian** [Lagg/steamodd#25]
Does this project have any documentation?

**Comment by ondrowan** [comment]
FYI, I have finally some time and started a sphinx docs branch: https://github.com/ondrowan/steamodd/tree/sphinx. I'll hopefully open a PR this weekend.

**Comment by Lagg** [comment]
Looking forward to it. Great timing too since I opened a readthedocs.org account a little while ago.

**Comment by Lagg** [comment]
Okay so I'm not really sure why this issue is still open, where my RTD for steamodd went or why I can't login. But I do intend to do a refactor/py2-compat-removal pass over steamodd next time I do a python project (currently doing stuff like [this](https://github.com/Lagg/steam-bot). And will revisit stuff like this then. Thx again @ondrowan
