### ISSUE TITLE
APIKEY should be obscured in travis config

### ISSUE THREAD

**Issue by FlaminSarge** [Lagg/steamodd#52]
https://github.com/Lagg/steamodd/blob/530f5d13bb06ace3a204b149ae4f18048fd92d0b/.travis.yml#L8

https://docs.travis-ci.com/user/encryption-keys/#Usage

Should be 
```
- secret: "<encryption of APIKEY=XYZ>"
```

**Comment by Lagg** [comment]
There was actually a reason I was doing this before due to support issues in travis. But I'm guessing they've solved them in the 5 years since this.

Given [my recent project](https://github.com/Lagg/steam-bot) and other non-py3 stuff I'm doing atm. I'll have to revisit when I do a "remove py2 compat hax and refactor" pass next time I do a python proj for steam.
